ALTER DATABASE logistics_db 
CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;

USE logistics_db;

DROP TABLE IF EXISTS kienhang;
DROP TABLE IF EXISTS donhang;
DROP TABLE IF EXISTS kho;
DROP TABLE IF EXISTS trangthai;
DROP TABLE IF EXISTS nhanviengiaohang;
DROP TABLE IF EXISTS phuongtien;
DROP TABLE IF EXISTS nhacungcap;
DROP TABLE IF EXISTS diachi;
DROP TABLE IF EXISTS phuong;
DROP TABLE IF EXISTS khachhang;
DROP TABLE IF EXISTS taikhoan;
DROP TABLE IF EXISTS vaitro;

CREATE TABLE vaitro (
    VT_Ma CHAR(5) PRIMARY KEY,
    VT_Ten VARCHAR(50) NOT NULL UNIQUE
)ENGINE=InnoDB;

CREATE TABLE taikhoan (
    TK_ID INT AUTO_INCREMENT PRIMARY KEY,
    TK_TenDangNhap VARCHAR(50) NOT NULL UNIQUE,
    TK_MatKhau VARCHAR(16) NOT NULL,
    VT_Ma CHAR(5) NOT NULL,
    FOREIGN KEY (VT_Ma) REFERENCES vaitro(VT_Ma)
)ENGINE=InnoDB;

CREATE TABLE khachhang (
    KH_ID INT AUTO_INCREMENT PRIMARY KEY,
    KH_Ten VARCHAR(50) NOT NULL,
    KH_SDT VARCHAR(12) NOT NULL UNIQUE,
    KH_Email VARCHAR(100) NOT NULL UNIQUE,
    TK_ID INT DEFAULT NULL,
    FOREIGN KEY (TK_ID) REFERENCES taikhoan(TK_ID)
)ENGINE=InnoDB;

CREATE TABLE phuong (
    PH_Ma CHAR(5) PRIMARY KEY,
    PH_Ten VARCHAR(50) NOT NULL UNIQUE
)ENGINE=InnoDB;

CREATE TABLE diachi (
    DC_ID INT AUTO_INCREMENT PRIMARY KEY,
    DC_SoNha VARCHAR(200) NOT NULL,
    PH_Ma CHAR(5) NOT NULL,
    KH_ID INT NOT NULL,
    FOREIGN KEY (PH_Ma) REFERENCES phuong(PH_Ma),
    FOREIGN KEY (KH_ID) REFERENCES khachhang(KH_ID)
)ENGINE=InnoDB;

CREATE TABLE nhacungcap (
    NCC_ID INT AUTO_INCREMENT PRIMARY KEY,
    NCC_Ten VARCHAR(100) NOT NULL,
    NCC_SDT VARCHAR(12) NOT NULL UNIQUE,
    NCC_Email VARCHAR(100) NOT NULL UNIQUE,
    NCC_TinhThanh VARCHAR(50) NOT NULL,
    TK_ID INT DEFAULT NULL,
    FOREIGN KEY (TK_ID) REFERENCES taikhoan(TK_ID)
)ENGINE=InnoDB;

CREATE TABLE phuongtien (
    PT_Ma CHAR(5) PRIMARY KEY,
    PT_Ten VARCHAR(50) NOT NULL UNIQUE
)ENGINE=InnoDB;

CREATE TABLE nhanviengiaohang (
    NVGH_Ma INT AUTO_INCREMENT PRIMARY KEY,
    NVGH_Ten VARCHAR(50) NOT NULL,
    NVGH_SDT VARCHAR(12) NOT NULL UNIQUE,
    NVGH_GioiTinh INT NOT NULL CHECK (NVGH_GioiTinh IN (0,1)),
    NVGH_NgaySinh DATE NOT NULL,
    NVGH_CCCD VARCHAR(12) NOT NULL UNIQUE,
    NVGH_AnhChanDung VARCHAR(100) NOT NULL,
    PT_Ma CHAR(5) NOT NULL,
    TK_ID INT DEFAULT NULL,
    FOREIGN KEY (PT_Ma) REFERENCES phuongtien(PT_Ma),
    FOREIGN KEY (TK_ID) REFERENCES taikhoan(TK_ID)
)ENGINE=InnoDB;

CREATE TABLE kho (
    K_Ma CHAR(5) PRIMARY KEY,
    K_Ten VARCHAR(50) NOT NULL UNIQUE,
    K_DiaChi VARCHAR(200) NOT NULL,
    K_ToaDo VARCHAR(100) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE trangthai (
    TT_Ma CHAR(5) PRIMARY KEY,
    TT_Ten VARCHAR(50) NOT NULL UNIQUE
)ENGINE=InnoDB;

CREATE TABLE donhang (
    DH_Ma CHAR(10) PRIMARY KEY,
    DH_MaQR VARCHAR(100) NOT NULL,
    DH_SoLuongKIH INT NOT NULL CHECK (DH_SoLuongKIH > 0),
    DH_TongTien FLOAT NOT NULL CHECK (DH_TongTien >= 0),
    DH_ToaDoDi VARCHAR(100) NOT NULL,
    DH_ToaDoDen VARCHAR(100) NOT NULL,
    DH_GhiChu VARCHAR(200) DEFAULT NULL,
    KH_ID INT NOT NULL,
    NVGH_Ma INT DEFAULT NULL,
    NCC_ID INT NOT NULL,
    TT_Ma CHAR(5) NOT NULL,
    K_Ma CHAR(5) NOT NULL,
    FOREIGN KEY (KH_ID) REFERENCES khachhang(KH_ID),
    FOREIGN KEY (NVGH_Ma) REFERENCES nhanviengiaohang(NVGH_Ma),
    FOREIGN KEY (NCC_ID) REFERENCES nhacungcap(NCC_ID),
    FOREIGN KEY (TT_Ma) REFERENCES trangthai(TT_Ma),
    FOREIGN KEY (K_Ma) REFERENCES kho(K_Ma)
)ENGINE=InnoDB;

CREATE TABLE kienhang (
    KIH_ID INT AUTO_INCREMENT PRIMARY KEY,
    KIH_TrongLuong FLOAT NOT NULL CHECK (KIH_TrongLuong > 0),
    KIH_ChieuDai FLOAT NOT NULL CHECK (KIH_ChieuDai > 0),
    KIH_ChieuRong FLOAT NOT NULL CHECK (KIH_ChieuRong > 0),
    KIH_ChieuCao FLOAT NOT NULL CHECK (KIH_ChieuCao > 0),
    KIH_DeVo INT NOT NULL CHECK (KIH_DeVo IN (0,1)),
    KIH_CoGiaTri INT NOT NULL CHECK (KIH_CoGiaTri IN (0,1)),
    KIH_GiaTien FLOAT NOT NULL CHECK (KIH_GiaTien >= 0),
    KIH_Anh VARCHAR(100) NOT NULL,
    KIH_MoTa VARCHAR(200) DEFAULT NULL,
    DH_Ma CHAR(10) NOT NULL,
    FOREIGN KEY (DH_Ma) REFERENCES donhang(DH_Ma)
)ENGINE=InnoDB;
